spring:
  application:
    name: eureka-server
# See EurekaClientConfigBean
eureka:
   instance:
#     prefer-ip-address: true
#     instance-id: ${spring.cloud.client.ipAddress}:${server.port}
     hostname: virtualhost
   client:
      register-with-eureka: true
      serviceUrl:
          defaultZone: http://host:8761/eureka/
server:
   port: 8761
