spring:
  application:
    name: eureka-server
eureka:
   instance:
     # See  EurekaInstanceConfigBean
#     prefer-ip-address: true
#     instance-id: ${spring.cloud.client.ipAddress}:${server.port}
     hostname: host
   client:
      register-with-eureka: true
      serviceUrl:
         defaultZone: http://virtualhost:8761/eureka/
server:
   port: 8761
